### PR TITLE
test: use `.order_by()` instead of the deprecated `.sort_by()` calls

### PR DESCRIPTION
**Pull request by kszucs**
These deprecated calls are going to be removed in https://github.com/ibis-project/ibis/pull/5850

### CODE REVIEW

**Review by gforsyth — APPROVED** [review]
:shipit:

**Comment by gforsyth** [comment]
Hmm, scratch that

**Comment by gforsyth** [comment]
thanks @kszucs !

**Comment by kszucs** [comment]
Thanks @gforsyth!

**Pull request merged**
